token          = "xxx-xxx--BJz7gKLXFVhEJU3vHUU6DkzKxxxxxxxx"
subnetid       = "subnet-0f8ff994cxxxxxx"
security_group = "sg-07f5fe497xxxxxxx"
region         = "us-east-2"
account        = "account-xxxxxxxxxx"
vpcid          = "vpc-011725f00xxxxxxxx"
